### ISSUE TITLE
Plugin 3 state all open browser no download file

### ISSUE THREAD

**Issue by cddehsy** [gautamkrishnar/motrix-webextension#50]
Close motrix, plugin 3 status all open, then click download, browser does not download the file. Close Extension Status, the browser can download normally.

https://drive.google.com/file/d/1n-JsypzM6tPlUp3jWNG_fmvDIf2lIyxW/view?usp=sharing

**Comment by gautamkrishnar** [comment]
@cddehsy From the video you shared, I can see that the Motrix is not running. Can you please open it and keep it in the background so that extension can work. Mac shows a dot under the icon when the motrix is running:
<img width="154" alt="Screenshot 2021-10-06 at 10 57 20 AM" src="https://user-images.githubusercontent.com/8397274/136145489-eb94feef-0836-42b8-a8f6-3081ea8c0e36.png">

**Comment by cddehsy** [comment]
@gautamkrishnar I mean without running the software, the browser will not be able to download the file, you must close the plug-in Extension Status browser to download properly

**Comment by gautamkrishnar** [comment]
@cddehsy also when you disable the extension status, it is disabling the entire extension itself. That is the reason why the download is working fine. 
![Screenshot 2021-10-09 at 2 15 00 PM](https://user-images.githubusercontent.com/8397274/136651295-c9765cd7-d2fa-4900-af5d-1ca1c8549906.png)
